/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.8.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as tasks from "../tasks.js";
import type * as users from "../users.js";
import type * as projects from "../projects.js";
import type * as content from "../content.js";
import type * as calendar from "../calendar.js";
import type * as memory from "../memory.js";
import type * as team from "../team.js";
import type * as seedTeam from "../seedTeam.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage for example:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  tasks: typeof tasks;
  users: typeof users;
  projects: typeof projects;
  content: typeof content;
  calendar: typeof calendar;
  memory: typeof memory;
  team: typeof team;
  seedTeam: typeof seedTeam;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;